site_name: Hyper Protect Virtual Server Workshop
repo_url: https://github.ibm.com/wsc-blockchain-and-digital-assets/hyper-protect-virtual-server-workshop.git
edit_uri: ''
nav:
    - Home: index.md
    - Pre-requisites: prereq.md
    - Secure Image Build Lab: securebuild.md
    - GREP11 Lab: grep11.md
    - Glossary of terms: glossary.md
    - Other Resources: resources.md

theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
