site_name: Hyper Protect Virtual Servers (HPVS) Workshop
repo_url: https://github.com/ibm-wsc/hyper-protect-virtual-servers-workshop
edit_uri: edit/master/docs
nav:
    - Home: index.md
    - Lab Assignments: assignment.md
    - GREP11 Lab:
      - Lab overview: grep11-lab/overview.md
      - How to set up a GREP11 server: grep11-lab/grep11-setup.md
      - Displaying your GREP11 environment: grep11-lab/grep11-display.md
      - Run the GREP11 sample code: grep11-lab/run-grep11-samples.md
      - Run the Lab exercises:
        - An overview of the Exercises: grep11-lab/exercise-overview.md
        - Exercise 1 (List PKCS Mechanisms): grep11-lab/lab-exercise1.md
        - Exercise 2 (Encryption and Decryption): grep11-lab/lab-exercise2.md
        - Exercise 3 (Sign and Verify): grep11-lab/lab-exercise3.md
        - Exercise 4 (Wrap and Unwrap Key): grep11-lab/lab-exercise4.md
    - Secure Image Build Lab:
      - Prerequisites: prerequisites.md
      - Hyper Protect Virtual Servers (HPVS) Lab Process Overview: securebuild-lab/overview.md
      - Configuring your Environment: securebuild-lab/securebuild-setup.md
      - Create your HPVS Secure Build Server: securebuild-lab/create-server.md
      - Securely Build your Application: securebuild-lab/build.md
      - Deploy your Securely Built Application as a Hyper Protect Virtual Server: securebuild-lab/deploy-app.md
      - Welcome to the Secure Bitcoin Wallet on IBM LinuxONE: securebuild-lab/bitcoin_wallet.md
      - Clean up your Environment: securebuild-lab/cleanup.md
    - Glossary of terms: glossary.md
    - Other resources: resources.md
    - Propose a change: proposechange.md

theme: 
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: yellow
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  favicon: images/hpvs-logo.svg
  logo: images/hpvs-logo.svg
  features:
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - search.share
    - navigation.indexes
    - announce.dismiss
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm-wsc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/s390x
  analytics:
    provider: google
    property: G-N1XCHYKZ2T
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/ibm-wsc/hyper-protect-virtual-servers-workshop/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make the documentation as good as possible.

markdown_extensions:
  - abbr
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - attr_list
  - tables
  - toc:
      permalink: true
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - print-site:
      add_to_navigation: true