site_name: Hyper Protect Virtual Server Workshop
repo_url: https://github.ibm.com/wsc-blockchain-and-digital-assets/hyper-protect-virtual-server-workshop.git
edit_uri: edit/master/docs
nav:
    - Home: index.md
    - Pre-requisites: prereq.md
    - Secure Image Build Lab: securebuild.md
    - GREP11 Lab: grep11.md
    - Glossary of terms: glossary.md
    - Other Resources: resources.md

theme: material
markdown_extensions:
  - admonition
  - toc:
      permalink: true
