site_name: Hyper Protect Virtual Server Workshop
repo_url: https://github.ibm.com/wsc-blockchain-and-digital-assets/hyper-protect-virtual-server-workshop
edit_uri: edit/master/docs
nav:
    - Home: index.md
    - Prerequisites: prerequisites.md
    - Secure Image Build Lab:
      - Process Overview: securebuild-lab/overview.md
      - Configuring your Environment: securebuild-lab/securebuild-setup.md
      - Create your Secure Build server: securebuild-lab/create-server.md
      - Securely Build your Image: securebuild-lab/build.md
      - Verify your Image Build: securebuild-lab/manifest.md
      - Deploy your Application in HPVS: securebuild-lab/deploy-app.md
    - GREP11 Lab: grep11.md
    - Glossary of terms: glossary.md
    - Other resources: resources.md
    - Propose a change: proposechange.md

theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
